-- CreateTable
CREATE TABLE "Comment" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "payload" TEXT NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL,
    "tweetNo" INTEGER NOT NULL,
    "userNo" INTEGER NOT NULL,
    CONSTRAINT "Comment_tweetNo_fkey" FOREIGN KEY ("tweetNo") REFERENCES "Tweet" ("tweet_no") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Comment_userNo_fkey" FOREIGN KEY ("userNo") REFERENCES "User" ("user_no") ON DELETE CASCADE ON UPDATE CASCADE
);
